version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - 'http.host=0.0.0.0'
      - 'transport.host=127.0.0.1'
      - 'ELASTIC_PASSWORD=${PASSWORD}'
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    environment:
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=${PASSWORD}
    ports:
      - '5601:5601'
    depends_on:
      - 'elasticsearch'

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    environment:
      - 'xpack.monitoring.elasticsearch.password=${PASSWORD}'
    volumes:
      - ./esconfig/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5000:5000
    depends_on:
      - 'elasticsearch'
      - 'setup_logstash'

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:${HEARTBEAT_VERSION}
    container_name: heartbeat
    depends_on: 
      - 'elasticsearch'
      - 'setup_heartbeat'

  # Run a short-lived container to set up Logstash.
  setup_logstash:
    image: centos:7
    volumes:
      - './escripts/setup-logstash.sh:/usr/local/bin/setup-logstash.sh:ro'
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-logstash.sh | tr -d "\r" | bash']
    environment:
      - 'ELASTIC_PASSWORD=duFfimm0'
    depends_on:
      - 'elasticsearch'

  setup_kibana:
    image: centos:7
    volumes:
      - './escripts/setup-kibana.sh:/usr/local/bin/setup-kibana.sh:ro'
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-kibana.sh | tr -d "\r" | bash']
    environment:
      - 'ELASTIC_PASSWORD=${PASSWORD}'
    depends_on:
      - 'elasticsearch'

  setup_heartbeat:
    image: docker.elastic.co/beats/heartbeat:${HEARTBEAT_VERSION}
    container_name: setup_heartbeat
    volumes: 
      - './scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro'
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-beat.sh | tr -d "\r" | bash -s heartbeat']
    depends_on: 
      - 'kibana'